[mysql]
host="localhost"
port=3306
database="stocks_algo"
user="root"
password=""

[db_tables]
user_table="user"
access_token_table="zerodha_creds"
customer_table="customer"

[mail]
mail_id = "stockanalyser2022@gmail.com"
password_token = "mualxdoewwkpekma"