# The TLS17 project configuration file
# This file is used for the database configuration ,Using this configuration file the-
# -TLS17 algorithm can able store its live candlestick data into database, 
# which is used trading algorithm to perform live trades using specific strategies.

#----------------------------------------------------------------------------------------

# Auther = Chetan Arvind Londhe
# Auther Mail = chetanlondhe1112@gmail.com
# version = 0.0

#----------------------------------------------------------------------------------------

# Database server details
# user,password,host,port,database
[db_server]
host="localhost"
port=3306
database="stocks dashboard"
user="root"
password=""



# Database tables details
[db_tables]
master_table = "master_sheet_table"
filter_table = "master_filter"
query_table = "query_storage"
user_table = "user_login"
news_table="news"
sentiment_table="sentiment_analysis"
mf_sheet_table="mf_sheet_table"
mf_filter_table="mf_master_filter"
mf_rolling_return_table="mf_rr_sheet_table"
portfolio_table = ""
mf_reports_table="mf_reports_tables"

#----------------------------------------------------------------------------------------

# How to access TOML file in python
# import tomllib
# with open("toml_file_path","rb") as toml:
#   toml_dict=tomllib.load(toml)
# print(toml_dict)  # to access whole toml object
# print(toml_dict["section_name"]["key_name"]["value_location(in integer)"])    # to access single value

#========================================================================================
# Old version bugs
[old_version_problems]
bug="old version 0.0 were facing issues regaring '----' lines these line are not good in toml file,so its updated with # at first location in these lines"